version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - REBUILD_INDEX=${REBUILD_INDEX:-true}
      - MAX_CHUNKS=${MAX_CHUNKS:-200}
      - CHROMA_DB_DIR=/data/chroma
    volumes:
      - chroma_data:/data/chroma
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=http://localhost:8000
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  chroma_data:
    driver: local


